# Generated by Django 4.1.3 on 2023-03-20 12:33

from django.db import migrations


def adding_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    categories = [
        Category(name='Дом'),
        Category(name='Работа', ),
        Category(name='Покупки'),
        Category(name='Хобби'),
        Category(name='Другое'),
    ]
    Category.objects.bulk_create(categories)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adding_categories),
    ]
