# Generated by Django 3.2.4 on 2023-03-19 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата исполнения'),
        ),
    ]
