# Generated by Django 3.2.4 on 2023-03-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Задача'),
        ),
    ]
