# Generated by Django 3.2.4 on 2023-03-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230322_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='error_text',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Текст ошибки'),
        ),
    ]
