# Generated by Django 3.2.4 on 2023-03-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_error_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='result',
        ),
        migrations.AddField(
            model_name='notification',
            name='task_result_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID результата выполнения задачи'),
        ),
    ]
