# Generated by Django 3.2.4 on 2023-03-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230322_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
