# Generated by Django 3.1.1 on 2021-01-12 02:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название поля')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('planned', 'PLANNED'), ('in work', 'IN WORK'), ('finished', 'FINISHED')], max_length=8, verbose_name='Статус задачи')),
                ('planned_finish', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 12))], verbose_name='Планируемая дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256, verbose_name='Название задачи')),
                ('task_description', models.TextField(verbose_name='Описание заадчи')),
                ('task_status', models.CharField(choices=[('new', 'NEW'), ('planned', 'PLANNED'), ('in work', 'IN WORK'), ('finished', 'FINISHED')], max_length=8, verbose_name='Статус задачи')),
                ('task_planned_finish', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 12))], verbose_name='Планируемая дата завершения')),
                ('change_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения задачи')),
                ('changed_fields', models.ManyToManyField(to='api.Fields', verbose_name='Измененные поля')),
                ('changed_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_change', to='api.tasks', verbose_name='Задача')),
            ],
        ),
    ]
