# Generated by Django 3.1.1 on 2020-10-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('planned', 'PLANNED'), ('in work', 'IN WORK'), ('finished', 'FINISHED')], max_length=8)),
                ('planned_finish', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('new', 'NEW'), ('planned', 'PLANNED'), ('in work', 'IN WORK'), ('finished', 'FINISHED')], max_length=8)),
                ('task_planned_finish', models.DateField()),
                ('change_created', models.DateTimeField(auto_now=True)),
                ('changed_fields', models.ManyToManyField(to='api.Fields', verbose_name='Измененные поля')),
                ('changed_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fff', to='api.tasks')),
            ],
        ),
    ]
