# Generated by Django 3.1.1 on 2021-01-14 01:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchanges',
            name='changed_fields',
        ),
        migrations.AlterField(
            model_name='taskchanges',
            name='task_planned_finish',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 14))], verbose_name='Планируемая дата завершения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='planned_finish',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 14))], verbose_name='Планируемая дата завершения'),
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
