# Generated by Django 3.1.1 on 2020-10-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchanges',
            name='changed_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_change', to='api.tasks'),
        ),
    ]
