# Generated by Django 3.1.1 on 2020-10-06 14:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201006_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchanges',
            name='task_planned_finish',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 10, 6))]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='planned_finish',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 10, 6))]),
        ),
    ]
