# Generated by Django 3.2.4 on 2023-03-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название')),
                ('status', models.CharField(blank=True, choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('error', 'Ошибка')], default='planned', max_length=30, verbose_name='Статус')),
                ('launch_time', models.DateTimeField(blank=True, null=True, verbose_name='Время запуска')),
                ('error_text', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Текст ошибки')),
                ('task_result_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID результата выполнения задачи')),
                ('task', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
